// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4PviVl3YBP4NxsZOr28omEX8wqo8lmX8',
    appId: '1:133974567795:web:db66981b98b31f82fc7306',
    messagingSenderId: '133974567795',
    projectId: 'cisonesse-app',
    authDomain: 'cisonesse-app.firebaseapp.com',
    storageBucket: 'cisonesse-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_64aN2MyRJhq1vzbt2kCA40hlsLX8H_c',
    appId: '1:133974567795:android:6d8772b2608620a4fc7306',
    messagingSenderId: '133974567795',
    projectId: 'cisonesse-app',
    storageBucket: 'cisonesse-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlIuS3aoXvg0w3YHNM5LwnPC9pGXZqD8E',
    appId: '1:133974567795:ios:347f45e645970ad6fc7306',
    messagingSenderId: '133974567795',
    projectId: 'cisonesse-app',
    storageBucket: 'cisonesse-app.firebasestorage.app',
    iosBundleId: 'com.example.cisonesseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlIuS3aoXvg0w3YHNM5LwnPC9pGXZqD8E',
    appId: '1:133974567795:ios:347f45e645970ad6fc7306',
    messagingSenderId: '133974567795',
    projectId: 'cisonesse-app',
    storageBucket: 'cisonesse-app.firebasestorage.app',
    iosBundleId: 'com.example.cisonesseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4PviVl3YBP4NxsZOr28omEX8wqo8lmX8',
    appId: '1:133974567795:web:ce8418f57e5ae812fc7306',
    messagingSenderId: '133974567795',
    projectId: 'cisonesse-app',
    authDomain: 'cisonesse-app.firebaseapp.com',
    storageBucket: 'cisonesse-app.firebasestorage.app',
  );
}
